services:
  db:
    image: postgres:15-alpine
    container_name: pos_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pos_network

  api:
    build: ./app
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    deploy:
      replicas: 3
    ports:
      - "8080-8082:3000"
    depends_on:
      - db
    networks:
      - pos_network

volumes:
  postgres_data:
    driver: local

networks:
  pos_network:
    driver: bridge
